name: github pages

on:
  push:
    skip-checks: true
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: generate
      run: npm run generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./docs